[package]
authors = ["Sebastien Rousseau"]
categories = ["development-tools"]
description = "Highly Performant Utility And Wrapper Functions Library For Rust"
documentation = "https://docs.rs/mini-functions"
edition = "2021"
homepage = "https://minifunctions.com"
include = [
    "/build.rs",
    "/Cargo.toml",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/README.md",
    "/src/**",
    "/tests/**",
]
keywords = ["functions"]
license = "Apache-2.0 OR MIT"
name = "mini-functions"
readme = "README.md"
repository = "https://github.com/sebastienrousseau/mini-functions.git"
rust-version = "1.57.0"
version = "0.0.8"

[dependencies]
date = { path = "./date" }
games = { path = "./games" }
hash = { path = "./hash" }
jot = { path = "./jot" }
claims = { path = "./claims" }
errors = { path = "./errors" }
logger = { path = "./logger" }
qr = { path = "./qr" }
random = { path = "./random" }
md5 = { path = "./md5" }

[workspace]
resolver = "1"
members = [
    "date",
    "games",
    "hash",
    "claims",
    "errors",
    "jot",
    "logger",
    "qr",
    "random",
    "md5",
] # List of workspace members

[workspace.package]
rust-version = "1.64"

[badges]
maintenance = { status = "actively-developed" }

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = 'unwind'
rpath = false
strip = false

[profile.release]
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
debug = false # Disable debug information
debug-assertions = false # Disable debug assertions
incremental = false # Disable incremental compilation
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
overflow-checks = false # Disable overflow checks
panic = "abort" # Strip expensive panic clean-up logic
rpath = false # Disable rpath
strip = "symbols"  # Automatically strip symbols from the binary.

[profile.test]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
rpath = false
strip = false

[lib]
crate-type = ["lib"]
path = "src/lib.rs"
required-features = [
    "date",
    "hash",
    "claims",
    "errors",
    "jot",
    "logger",
    "qrcode",
    "random",
    "md5",
]
