[package]
authors = ["Sebastien Rousseau"]
categories = ["development-tools"]
description = "Highly Performant Utility And Wrapper Functions Library For Rust"
documentation = "https://docs.rs/mini-functions"
edition = "2021"
homepage = "https://minifunctions.com"
include = [
    "/build.rs",
    "/Cargo.toml",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/README.md",
    "/src/**",
    "/tests/**",
]
keywords = ["functions"]
license = "Apache-2.0 OR MIT"
name = "mini-functions"
readme = "README.md"
repository = "https://github.com/sebastienrousseau/mini-functions.git"
rust-version = "1.57.0"
version = "0.0.8"

[dependencies]
mini-functions-date = { path = "./mini-functions-date" }
mini-functions-jwt = { path = "./mini-functions-jwt" }
mini-functions-jwt-claims = { path = "./mini-functions-jwt-claims" }
mini-functions-jwt-errors = { path = "./mini-functions-jwt-errors" }
cargo-make = "0.36.3"

[tasks.build]
description = "Build libraries for target platform and architecture"
dependencies = ["build-linux", "build-macos", "build-windows"]

[tasks.build-linux]
description = "Build libraries for Linux"
command = "cargo build --target x86_64-unknown-linux-gnu"

[tasks.build-macos]
description = "Build libraries for macOS"
command = "cargo build --target x86_64-apple-darwin"

[tasks.build-windows]
description = "Build libraries for Windows"
command = "cargo build --target x86_64-pc-windows-gnu"

[workspace]
resolver = "1"
members = [
    "mini-functions-date",
    "mini-functions-jwt-claims",
    "mini-functions-jwt-errors",
    "mini-functions-jwt",
] # List of workspace members

[workspace.package]
rust-version = "1.64"

[badges]
maintenance = { status = "actively-developed" }

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = 'unwind'
rpath = false
strip = false

[profile.release]
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
debug = false # Disable debug information
debug-assertions = false # Disable debug assertions
incremental = false # Disable incremental compilation
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
overflow-checks = false # Disable overflow checks
panic = "abort" # Strip expensive panic clean-up logic
rpath = false # Disable rpath
strip = "symbols"  # Automatically strip symbols from the binary.

[profile.test]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
rpath = false
strip = false

[lib]
crate-type = ["lib"]
path = "src/lib.rs"
required-features = [
    "mini-functions-date",
    "mini-functions-jwt-claims",
    "mini-functions-jwt-errors",
    "mini-functions-jwt"
]
